### ISSUE TITLE
(Android) NullPointerException when task finishes

### ISSUE THREAD

**Issue by cbenhagen** [hnvn/flutter_downloader#10]
Device: Emulated Pixel 2 with API 28

```
W/System.err(15204): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err(15204): 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
W/System.err(15204): 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
W/System.err(15204): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.getOpenFileIntent(DownloadWorker.java:272)
W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:161)
W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:84)
W/System.err(15204): 	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:192)
W/System.err(15204): 	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:105)
W/System.err(15204): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(15204): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(15204): 	at java.lang.Thread.run(Thread.java:764)
I/WorkerWrapper(15204): Worker result FAILURE for Work [ id=f27e5d6b-a588-4ee3-886e-74220a3f6a2c, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
```

**Comment by hnvn** [comment]
Have you added `provider` to your `manifest` ? (see Android integration instruction for detail)

**Comment by cbenhagen** [comment]
No but I also do not want to open files on click but wasn't aware that `clickToOpenDownloadedFile` is set to `true` by default. Setting it to `false` fixes the issue.

**Comment by zouzhenglu** [comment]
> Device: Emulated Pixel 2 with API 28
> 
> ```
> W/System.err(15204): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
> W/System.err(15204): 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
> W/System.err(15204): 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
> W/System.err(15204): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
> W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.getOpenFileIntent(DownloadWorker.java:272)
> W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:161)
> W/System.err(15204): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:84)
> W/System.err(15204): 	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:192)
> W/System.err(15204): 	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:105)
> W/System.err(15204): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> W/System.err(15204): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> W/System.err(15204): 	at java.lang.Thread.run(Thread.java:764)
> I/WorkerWrapper(15204): Worker result FAILURE for Work [ id=f27e5d6b-a588-4ee3-886e-74220a3f6a2c, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
> ```

I have this problem, too. How did you solve it?
