### ISSUE TITLE
Add Ref and/or URL and/or Filename to DownloadTask object

### ISSUE THREAD

**Issue by codmajik** [hnvn/flutter_downloader#13]
Adding a ref and/or  url and/or filename will make using this library easier as the user wont have to manage the tasks in their app.

Like the example in the repo which saves the tasks in a json file, that wont be needed anymore if there is user provided ref or filename or url in DownloadTask object.

Great library BTW.

**Comment by hnvn** [comment]
This feature will be supported in the new release

**Comment by SPK-RPI** [comment]
Future<String> downloadFile(int index) async {
    final task = FlutterDownloader.enqueue(
        url: syllabus[index]["url"],
        fileName: syllabus[index]["filename"],
        openFileFromNotification: true,
        showNotification: true,

        savedDir: filepath);
    return task;
  }

shows error download failed
