### ISSUE TITLE
handle notification on click action

### ISSUE THREAD

**Issue by aravindhkumar23** [hnvn/flutter_downloader#4]
Is it possible to open the particular downloaded file by using path or open my app when the user clicks on the notification on download success?

**Comment by hnvn** [comment]
it's possible to navigate a user to a specific UI when the user clicks on the notification by using PendingIntent. It's easy to do on the native side, but I wonder how to do it in case of Flutter

**Comment by marica27** [comment]
May I ask you, why didn't you use [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager) for Android? It's feels like that it would be possible to open file from notification.
> Apps that request downloads through this API should register a broadcast receiver for ACTION_NOTIFICATION_CLICKED to appropriately handle when the user clicks on a running download in a notification or from the downloads UI.

I have a related question. As I am not familiar with Android, I don't know default behaviour. If app downloads image does it need to register broadcast receiver to open image in standard gallery?

**Comment by hnvn** [comment]
WorkManager gives me more controlling of my downloading task, for example: tracking the progress of downloading, customizing the UI of notification and handling click on the notification. My library is lack of handling for an action of clicking on the notification of a completed download task. I have a plan to update for this feature but I want to find a proper way to deal with it friendly for Flutter. Opening an application to view the downloaded file is just a use-case, some people would like to drive user back to Flutter activity. I will try and update it as soon as possible. Thanks for your feedback.

**Comment by hnvn** [comment]
This feature is supported in new version. Thanks for for your feedback.

**Comment by Tanvir3488** [comment]
I have Follow This instruction properly this file download showing in the notification But Not opening that file & i can find downloaded file in file manager can you please help

**Comment by Akshat7321** [comment]
Is the issue resolved ?
