### ISSUE TITLE
There is sound notifications during downloading

### ISSUE THREAD

**Issue by marica27** [hnvn/flutter_downloader#5]
When file is in process of downloading there is a sound for every batch of data
```
I/flutter ( 1201): Download task (c49d7308-7b8f-4654-8281-d55bcc74cbe8) is in status (DownloadTaskStatus(2)) and process (56)
W/Notification( 1201): Use of stream types is deprecated for operations other than volume control
W/Notification( 1201): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
```
I use
Flutter (Channel dev, v0.5.7, on Mac OS X 10.12.6 16G29, locale en-NL)
 Android toolchain - develop for Android devices (Android SDK 27.0.3)

And I run your package on Android devices only - emulator Nexus 5 and my mobile Samsung Galaxy S7.

**Comment by hnvn** [comment]
The problem comes from setting the priority of Notification from Android O. I haven't ever tested on that OS version, but it should be fixed by adding a line of code. I have just published a new version to fix it. Let me know if it works

**Comment by marica27** [comment]
yep. It is fixed. I've checked only on devices that I mentioned above.
