### ISSUE TITLE
(iOS) Crash when opening app with previously unfinished tasks 

### ISSUE THREAD

**Issue by cbenhagen** [hnvn/flutter_downloader#7]
To reproduce:
1. Schedule tasks
2. Quit app
3. Start app

Flutter_downloader version used: 0.1.0

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001126777f6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001117f1035 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112677675 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001112b2422 -[NSURL(NSURL) initFileURLWithPath:] + 127
	4   Foundation                          0x00000001112b2c8e +[NSURL(NSURL) fileURLWithPath:] + 45
	5   Runner                              0x000000010f9ec3ca -[FlutterDownloaderPlugin URLSession:downloadTask:didFinishDownloadingToURL:] + 682
	6   CFNetwork                           0x000000011757c5f8 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38
	7   Foundation                          0x000000011125f2b7 __NS<…>
```

**Comment by cbenhagen** [comment]
@hnvn I tried to dig into this issue. One thing I missed in the original report is this line which only prints when the app is being run from Xcode:
` *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'`

The problem is here on line 222:
https://github.com/hnvn/flutter_downloader/blob/f8fa727c9f4a48cbf2b0d18b23feb20416fb85b6/ios/Classes/FlutterDownloaderPlugin.m#L211-L222

`_downloadInfo` is not being saved when the app is being suspended. So when a download finishes and the completion handler gets called we do not know where to move the file. Maybe this info can be saved in the task itself? In the session? Or should this info be saved in an SQLite db like on android?

**Comment by hnvn** [comment]
It will be fixed in the new release.

**Comment by bhavin-concetto** [comment]
@hnvn  Is it fixed because I am getting the same error in the 1.8.4 version? Do you have any quick fixes?
@cbenhagen Have you found the solution?

**Comment by Maxdegreat** [comment]
it is not fixed

**Comment by Maxdegreat** [comment]
ill try nd update if I resolve the issue

**Comment by bhavin-concetto** [comment]
@Maxdegreat Have you able to find out?
