### ISSUE TITLE
(iOS) Tasks do not run when application has quit

### ISSUE THREAD

**Issue by cbenhagen** [hnvn/flutter_downloader#8]
`Background fetch` and `Remote notifications` are enabled. `AppDelegate.m` looks like this:

```objective-c
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)(void))completionHandler {
    completionHandler();
}

@end
```
Maybe related to https://github.com/hnvn/flutter_downloader/issues/7?

**Comment by hnvn** [comment]
How did you quit your application? By pressing Home button or by killing it in the recent app screen?
iOS is not my domain of expertise but as far as I know, if you kill an application from the recent app screen, all of its background tasks will be terminated too. It's the design of iOS, if you implicitly terminate an application, it means you don't want that application run anymore (include all of its background tasks)

**Comment by cbenhagen** [comment]
Yes I killed it manually. Here are the [relevant docs](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW5):

>  If tasks have not yet finished and the system terminates your app, the system automatically continues managing the tasks in the background. If the user terminates your app, the system cancels any pending tasks.
